[package]
name = "baseimg"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.4"}
tokio = {version="1.37.0", features=["full"]}
zip = "1.3.1"
cvtool = {path="../../lib/cvtool"}
opencv = "0.91.3"
